### ISSUE TITLE
Quarkus support?

### ISSUE THREAD

**Issue by sengokudaikon** [Ahoo-Wang/Wow#655]
**Is your feature request related to a problem? Please describe.**
As far as I know, the project template and most configs work best with spring. I would like to use quarkus and try to use Wow with it. Is it supported?

**Describe the solution you'd like**
If the framework is agnostic in terms of integration, and doesn't depend on Spring, then perhaps a guide to integrate with Quarkus? If the framework does depend on spring, is it possible to make a version/compat patch for Quarkus?

**Describe alternatives you've considered**
Using spring, because of performance considerations decided to use Quarkus.

**Additional context**
Thank you for this work.

**Comment by Ahoo-Wang** [comment]
Sorry, due to time constraints, there are currently no plans to integrate this framework. If you know enough about Wow, you can choose to integrate it yourself.
